In [2]:
import numpy as np

## DataTypes & Attributes

In [3]:
# Create different NumPy arrays
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
# .shape attribute finds the shape of an array
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# .ndim attribute finds the dimension of an array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
# .dtype finds the type of the array
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
# .size finds the total number of elements in the array
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
# type() function finds the type of the array
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
# Create ndarray with all ones
ones = np.ones([2, 3])
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
# Create ndarray with all zeros
zeros = np.zeros([2, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# Create an array of different range of numbers
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
# Create an array of random integers
random_array = np.random.randint(1, 10, size=(3, 5))
random_array

array([[3, 5, 8, 3, 2],
       [4, 4, 6, 5, 3],
       [6, 1, 3, 8, 1]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
# Create an array of random float numbers
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.37802014, 0.2979256 , 0.67933669],
       [0.13018599, 0.86072267, 0.71450375],
       [0.48538717, 0.28858356, 0.37473135],
       [0.78954005, 0.01811232, 0.13889786],
       [0.22618464, 0.58756106, 0.4053575 ]])

In [26]:
random_array_2.shape

(5, 3)

In [27]:
# Another way of creating random float numbers
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.18340818, 0.59830695, 0.20280882],
       [0.89049452, 0.13988127, 0.4607023 ],
       [0.93074237, 0.82914612, 0.2504616 ],
       [0.79286372, 0.85950623, 0.2177519 ],
       [0.56160041, 0.36736673, 0.60151613]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=42)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [29]:
np.random.seed(7)

random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [30]:
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [31]:
# Find unique elements of the array
np.unique(random_array_4)

array([2, 3, 4, 5, 6, 7, 9])

In [32]:
a1

array([1, 2, 3])

In [33]:
a1.shape

(3,)

In [34]:
# Find first element in 1D vector or array in 1D+ matrices
a1[0]

1

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
a2.shape

(2, 3)

In [37]:
a2[0]

array([1. , 2. , 3.3])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a3.shape

(2, 3, 3)

In [40]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
# Find second array in the matrics
a2[1]

array([4. , 5. , 6.5])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
# Get the first two elements of all arrays in the matrics
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [45]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [46]:
a4.shape

(2, 3, 4, 5)

In [47]:
a4.ndim

4

In [48]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## Manipulating & comparing arrays

### Artithmetic

In [49]:
a1

array([1, 2, 3])

In [50]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [51]:
a1 + ones

array([2., 3., 4.])

In [52]:
a1 - ones

array([0., 1., 2.])

In [53]:
a1 * ones

array([1., 2., 3.])

In [54]:
a1

array([1, 2, 3])

In [55]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [56]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
# How can you reshape a2 to be compatible with a3?
# Search: How to reshape numpy array
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

In [ ]:
a2

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
a1 + ones

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
np.mod(a1, 2)

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

## Aggregation

Aggregation = performing the same operation on a number of things

In [ ]:
lst = [1, 2, 3]
type(lst)

In [ ]:
sum(lst)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

**Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy datatypes (`np.sum()`)**

In [ ]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array)  # Python's sum()
%timeit np.sum(massive_array)  # NumPy's np.sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degress to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping & transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3, 1)

In [ ]:
a2.reshape(2, 3, 1).shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)

In [ ]:
a2_reshape * a3

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
# Transpose = switch the axis
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.T

In [ ]:
a3.T.shape

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
# Transpose mat1
mat2.T

In [ ]:
mat2.T.shape

In [ ]:
mat1.shape, mat2.T.shape

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Dot product example (nut butter sales)

In [ ]:
np.random.seed(0)

# Number of jars sold
sale_amounts = np.random.randint(20, size=(5, 3))
sale_amounts

In [ ]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sale_amounts,
                           index=['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'],
                           columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
weekly_sales

In [ ]:
# Create prices array
prices = np.array([10, 8, 12])
prices

In [ ]:
prices.shape

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=['Price'],
                            columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
butter_prices

In [ ]:
sale_amounts.shape

In [ ]:
prices.shape

In [ ]:
total_sales = prices.dot(sale_amounts)

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sale_amounts.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices

In [ ]:
weekly_sales

In [ ]:
butter_prices.shape, weekly_sales.shape

In [ ]:
weekly_sales.T.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
# Doesn't work, not the right shape of daily_sales
weekly_sales['Total ($)'] = daily_sales

In [ ]:
# Try again with transpose
weekly_sales['Total ($)'] = daily_sales.T
weekly_sales

## Comparision operators

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 > a2

In [ ]:
bool_array = a1 >= a2
bool_array

In [ ]:
type(bool_array), bool_array.dtype

In [ ]:
a1 > 5

In [ ]:
a1 < 5

In [ ]:
a1 == a1

In [ ]:
a1

In [ ]:
a2

In [ ]:
a1 == a2

## Sorting arrays

In [ ]:
random_array = np.random.randint(10, size=(3, 5))
random_array

In [ ]:
# Sort array according to the element, from lowest to highest
np.sort(random_array)

In [ ]:
# Sort array according to the index of the element, lowest to highest
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [ ]:
# Find the index where the element has min value
np.argmin(a1)

In [ ]:
# Find the index where the element has max value
np.argmax(a1)

In [ ]:
random_array

In [ ]:
# Find the index where the element has max value in entire matrix
np.argmax(random_array)

In [ ]:
# Find the index of max elements in each array of matrix
# axis=0 means column-wise operation
np.argmax(random_array, axis=0)

In [ ]:
# Find the index of max elements in each array of matrix
# axis=1 means row-wise operation
np.argmax(random_array, axis=1)

## Practical Example

<img src='images/panda.png'/>

In [61]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread('images/panda.png')
print(type(panda))

<class 'numpy.ndarray'>


In [62]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [63]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [64]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src='images/car-photo.png' />

In [65]:
car = imread('images/car-photo.png')
print(type(car))

<class 'numpy.ndarray'>


In [67]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src='images/dog-photo.png' />

In [68]:
dog = imread('images/dog-photo.png')
print(type(dog))

<class 'numpy.ndarray'>


In [69]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274