<a href="https://colab.research.google.com/github/MuhammadAwon/backyard-projects/blob/main/intro-to-deep-learning/tensorflow_fundamentals/00_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

-----------------------------------------------------------------

In [ ]:
import numpy as np
import tensorflow as tf

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [ ]:
# Create scalar
scalar = tf.constant([8])
scalar

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>

In [ ]:
# Create vector
vector = tf.constant([1, 3, 5, 8, 14])
vector

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  3,  5,  8, 14], dtype=int32)>

In [ ]:
# Create matrix
matrix = tf.constant([[1, 3, 5],
                      [8, 14, 24]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  3,  5],
       [ 8, 14, 24]], dtype=int32)>

In [ ]:
# Create tensor
tensor = tf.constant([[[1, 3, 5],
                       [4, 6, 8]],
                      [[7, 9, 10],
                       [11, 34, 65]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  3,  5],
        [ 4,  6,  8]],

       [[ 7,  9, 10],
        [11, 34, 65]]], dtype=int32)>

2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
# Scalar
scalar, scalar.shape, scalar.ndim, tf.size(scalar)

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>,
 TensorShape([1]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
# Vector
vector, vector.shape, vector.ndim, tf.size(vector)

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  3,  5,  8, 14], dtype=int32)>,
 TensorShape([5]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=5>)

In [ ]:
# Matrix
matrix, matrix.shape, matrix.ndim, tf.size(matrix)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 1,  3,  5],
        [ 8, 14, 24]], dtype=int32)>,
 TensorShape([2, 3]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [ ]:
# Tensor
tensor, tensor.shape, tensor.ndim, tf.size(tensor)

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  3,  5],
         [ 4,  6,  8]],
 
        [[ 7,  9, 10],
         [11, 34, 65]]], dtype=int32)>,
 TensorShape([2, 2, 3]),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [ ]:
# Create first tensor with random values between 0 and 1 with shape (5, 300)
tf.random.set_seed(42)

first_tensor = tf.constant(np.random.random((5, 300)))
first_tensor

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[3.89420371e-01, 4.73529525e-01, 5.34871697e-02, ...,
        8.36284921e-01, 7.54168956e-01, 2.62424274e-01],
       [3.99023759e-01, 6.77236617e-01, 5.86878164e-01, ...,
        2.55656599e-01, 3.86279365e-01, 2.46010656e-01],
       [3.79255189e-01, 1.94205306e-04, 6.42983310e-02, ...,
        1.25141762e-01, 7.55292321e-01, 3.78293896e-01],
       [5.13051935e-01, 4.62328299e-01, 7.62019812e-01, ...,
        2.27474602e-01, 2.24920970e-01, 2.15475938e-01],
       [6.84696421e-01, 4.81303833e-01, 2.61470737e-01, ...,
        4.52219895e-01, 3.48076458e-01, 2.28830503e-01]])>

In [ ]:
# Create second tensor
tf.random.set_seed(0)

second_tensor = tf.constant(np.random.random((5, 300)))
second_tensor

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.63761812, 0.05957552, 0.82837321, ..., 0.75887938, 0.03251605,
        0.27140548],
       [0.6477235 , 0.73757453, 0.14090107, ..., 0.54058328, 0.20569447,
        0.61889926],
       [0.9493299 , 0.37039836, 0.49488955, ..., 0.26201286, 0.26055104,
        0.83602871],
       [0.79882155, 0.30072529, 0.44420783, ..., 0.43577296, 0.55190447,
        0.49650725],
       [0.4082457 , 0.76107095, 0.83329522, ..., 0.99090011, 0.89633739,
        0.45958035]])>

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tf.matmul(first_tensor, second_tensor, transpose_a=True)

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[1.55615815, 1.13337543, 1.36495364, ..., 1.51263832, 1.09042938,
        1.23912158],
       [1.30658547, 1.03313536, 1.09421668, ..., 1.40389966, 0.84132341,
        0.99856925],
       [1.19074165, 0.88802532, 0.71519715, ..., 0.96585283, 0.79413792,
        0.9300056 ],
       ...,
       [1.18395446, 0.697319  , 1.26858834, ..., 1.35286384, 0.64327149,
        0.81059426],
       [1.76986803, 0.94214917, 1.44290891, ..., 1.42195922, 0.73689915,
        1.34684366],
       [0.95134495, 0.57616001, 0.72566156, ..., 0.75190224, 0.48173237,
        0.75189512]])>

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(tf.transpose(first_tensor), second_tensor, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[1.55615815, 1.13337543, 1.36495364, ..., 1.51263832, 1.09042938,
        1.23912158],
       [1.30658547, 1.03313536, 1.09421668, ..., 1.40389966, 0.84132341,
        0.99856925],
       [1.19074165, 0.88802532, 0.71519715, ..., 0.96585283, 0.79413792,
        0.9300056 ],
       ...,
       [1.18395446, 0.697319  , 1.26858834, ..., 1.35286384, 0.64327149,
        0.81059426],
       [1.76986803, 0.94214917, 1.44290891, ..., 1.42195922, 0.73689915,
        1.34684366],
       [0.95134495, 0.57616001, 0.72566156, ..., 0.75190224, 0.48173237,
        0.75189512]])>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [ ]:
tf.random.set_seed(32)

third_tensor = tf.constant(np.random.random((224, 224, 3)))
third_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.327721  , 0.89798212, 0.64700936],
        [0.52321835, 0.28593823, 0.78621056],
        [0.91803812, 0.86038759, 0.08302567],
        ...,
        [0.46814834, 0.79392094, 0.0731721 ],
        [0.9417858 , 0.95136108, 0.99287006],
        [0.03129781, 0.27957326, 0.45773092]],

       [[0.24623337, 0.08122946, 0.71208252],
        [0.07738204, 0.5751598 , 0.51701962],
        [0.67480588, 0.82479867, 0.5394342 ],
        ...,
        [0.38434452, 0.7924645 , 0.49781339],
        [0.4865912 , 0.88856204, 0.37898757],
        [0.04572861, 0.96681767, 0.36122327]],

       [[0.32683307, 0.94824751, 0.02278872],
        [0.64661368, 0.33608893, 0.37300481],
        [0.31463962, 0.11523427, 0.78494274],
        ...,
        [0.35165188, 0.62487336, 0.46867357],
        [0.07430217, 0.88275576, 0.94326402],
        [0.93219615, 0.37131436, 0.39060745]],

       ...,

       [[0.05369993, 0.61807222, 0.07019633],
        [0.65

7. Find the min and max values of the tensor you created in 6.

In [ ]:
# Find min & max values
tf.reduce_min(third_tensor).numpy(), tf.reduce_max(third_tensor).numpy()

(3.6527698910049367e-07, 0.9999907175451467)

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [ ]:
tf.random.set_seed(42)

fourth_tensor = tf.constant(np.random.randint(low=1, high=100, size=(1, 224, 224, 3)))
fourth_tensor.shape

TensorShape([1, 224, 224, 3])

In [ ]:
# Squeeze the shape of fourth_tensor from (1, 224, 224, 3) to (224, 224, 3)
fourth_tensor = tf.squeeze(fourth_tensor)
fourth_tensor.shape

TensorShape([224, 224, 3])

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [ ]:
my_tensor = tf.constant([1, 2, 4, 5, 7, 24, 8, 10, 20, 23])
tf.argmax(my_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

10. One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(indices=my_tensor, depth=10)  # where depth == tf.size(my_tensor)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

------------

## 📖 Extra-curriculum

1. Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
2. Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
3. Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
4. Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.

---------

1. Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.

**tf.lookup()** finds the key-value pairs between two tensors. In order to find the value(s) of specified key(s), we have to initialize the key-value pair (in the form of a table) and make it static (immutable). This can be done in two steps:
1. [KeyValueTensorInitializer](https://www.tensorflow.org/api_docs/python/tf/lookup/KeyValueTensorInitializer) - Table initailizers given `keys` and `values` tensors.
2. [StaticHashTable](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable) - A generic hash table that is immutable once initialized.



In [ ]:
# Create tensors for keys, values, & input tensor to find the pair
keys_tensor = tf.constant(['Apple', 'Orange', 'Strawberry'])
vals_tensor = tf.constant([4, 2, 9])
input_tensor = tf.constant([['Apple', 'Blueberry'],
                            ['Kiwi', 'Orange'],
                            ['Strawberry', 'Peach']])

In [ ]:
# Initialize the key-value pair & make the table static (unchangeable)
init = tf.lookup.KeyValueTensorInitializer(keys=keys_tensor, values=vals_tensor)
hash_table = tf.lookup.StaticHashTable(init, default_value=0)

In [ ]:
# Find the values according to the keys
hash_table.lookup(input_tensor).numpy()

array([[4, 0],
       [0, 2],
       [9, 0]], dtype=int32)

**Note:** There will be TypeError if *keys* or *default_value* doesn't match the table data types.

In [ ]:
# Create key with wrong dytpe (will error)
hash_table.lookup(tf.constant([2])).numpy()

TypeError: ignored

In [ ]:
# Create static table with wrong dytpe of default_value (also will error)
wrong_hash_table = tf.lookup.StaticHashTable(init, default_value='Pineapple')
wrong_hash_table.lookup(input_tensor).numpy()

TypeError: ignored

Values can able be accessed with pure Python style.

In [ ]:
# Another way to access key-value pair
hash_table[tf.constant(['Apple', 'Orange', 'Strawberry', 'Mango', 'Banana'])].numpy()

array([4, 2, 9, 0, 0], dtype=int32)

2. Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?

In [ ]:
# Create function to calculate monthly grocery bill with @tf.function
@tf.function
def bill_calc(bill):
  return tf.reduce_sum(bill) * 30

# A series of grocery bill
grocery_tensor = tf.constant([2.34, 3.23, 1.00, 2.75, 2.00, 1.75, 8.99, 6.65, 5.50, 4.25])
bill_calc(grocery_tensor).numpy()

1153.7999

3. Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28, 28)),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.42959684, -0.87668973, -0.22993651, -0.85399234,  0.6358728 ,
         0.39069408, -0.35935575, -0.11145577,  0.58587086, -0.30370227]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.06653292, 0.04254678, 0.08123589, 0.04352352, 0.19309196,
        0.15110695, 0.07137431, 0.09145418, 0.1836744 , 0.07545915]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

1.8897674

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2999 - accuracy: 0.9124
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1452 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1076 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0880 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0739 - accuracy: 0.9764


In [ ]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0780 - accuracy: 0.9762


[0.07796626538038254, 0.9761999845504761]

In [ ]:
probability_model = tf.keras.Sequential([
                                         model,
                                         tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.9684455e-09, 4.4112838e-08, 2.4197052e-06, 1.1629232e-04,
        3.1816414e-11, 4.6222826e-07, 2.3899483e-12, 9.9987495e-01,
        3.2502382e-07, 5.5425176e-06],
       [2.8096802e-06, 9.6413205e-06, 9.9996591e-01, 1.8047607e-05,
        1.6593471e-15, 1.4258972e-06, 1.1139807e-06, 2.1944664e-14,
        1.0240865e-06, 2.9508493e-14],
       [2.4171047e-06, 9.9600106e-01, 4.7002998e-04, 4.3006567e-05,
        9.0361798e-05, 8.9604355e-06, 3.6490113e-05, 2.0338339e-03,
        1.3107827e-03, 3.0913561e-06],
       [9.9963117e-01, 3.2367353e-08, 8.8514862e-05, 9.6501276e-07,
        2.7238507e-06, 9.1205520e-06, 2.4562643e-04, 9.2692699e-06,
        3.1645050e-06, 9.3087710e-06],
       [1.9261597e-06, 7.1440009e-09, 1.4117220e-05, 4.2442207e-07,
        9.9096912e-01, 3.0366738e-08, 1.6503618e-05, 1.0644399e-04,
        5.6497834e-06, 8.8858064e-03]], dtype=float32)>

* Functions we have used:
  * `numpy()`, `tf.__version__`.

* Functions we haven't used yet:
  * `load_data()`, `keras.Sequential()`, `Flatten()`, `Dense()`, `Dropout()`, `tf.nn.softmax()`, `tf.keras.losses.SparseCategoricalCrossentropy()`, `compile()`, `fit()`, `evaluate()`.

* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.

---